- name: upgrade package for debian including ubuntu
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: upgrade package for RedHat including centos, fedora
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'
