---
# tasks file for dotfiles-chezmoi
- name: install chezmoi from snap
  become: true
  snap:
    name:
      - chezmoi
    classic: true

- name: download repo and apply
  command: "chezmoi init --apply --verbose {{ chezmoi_repo }}"