- name: install chezmoi from snap
  become: true
  community.general.snap:
    name:
      - chezmoi
    classic: true

- name: download repo and apply
  ansible.builtin.command: "chezmoi init --apply --verbose {{ chezmoi_repo }}"
  args:
    creates: ~/.config/chezmoi/chezmoistate.boltdb
