- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: timezone setup
  become: yes
  shell: timedatectl set-timezone {{ zone }}
  register: set_timezone
  changed_when: false

- name: locale setup
  become: yes
  shell: localectl set-locale LANG={{ locale }}
  register: set_locale
  changed_when: false
