- name: docker_host
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    update_cache: yes

- name: add apt-key
  become: yes
  apt_key:
    url: "{{ docker.key.url }}"
    id: "{{ docker.key.id }}"
    state: present

- name: add repository
  become: yes
  apt_repository:
    repo: "{{ docker.repo }}"

- name: install docker ce
  become: yes
  apt:
    name: docker-ce
    update_cache: yes

- name: add default user to docker group
  become: yes
  user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    append: yes

- name: install docker-compose
  become: yes
  get_url:
    url: "{{ docker_compose.url }}"
    dest: "{{ docker_compose.dest }}"
    mode: "{{ docker_compose.mode }}"

- name: install python3-docker
  become: yes
  apt:
    name: python3-docker
    update_cache: yes

- name: link docker config
  file:
    src: ~/.dotfiles/docker
    dest: ~/.docker
    state: link
