- name: setup sending syslog to remote host
  become: true
  template:
    src: templates/main.tmpl
    dest: /etc/rsyslog.d/10-remote.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart rsyslog
