- name: install software-properties-common
  become: true
  apt:
    name: software-properties-common
    update_cache: yes

- name: install common package
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ jammy_apt_packages }}"

- name: install common packages from snap
  become: true
  snap:
    name: "{{ item }}"
  loop: "{{ debian_snap }}"
