- name: install packages for debian
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: install packages for redhat
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'
