- name: emacs install
  become: true
  snap:
    name: emacs
    classic: true

- name: clone chemacs2
  git:
    repo: https://github.com/plexus/chemacs2.git
    dest: ~/.config/emacs
    version: 30a2

- name: make .config/chemacs directory
  file:
    path: ~/.config/chemacs
    state: directory

- name: copy profiles.el
  copy:
    src: profiles.el
    dest: ~/.config/chemacs/profiles.el

- name: clone emacs-cask setting
  git:
    repo: https://github.com/tateishi/emacs-cask.git
    dest: ~/.config/chemacs/cask

- name: clone cask
  git:
    repo: https://github.com/cask/cask.git
    dest: ~/.cask
