- name: emacs install
  include_tasks: emacs.yml
  when: emacs_default_config is defined and emacs_default_config

- name: chemacs install
  include_tasks: chemacs.yml
  when: emacs_default_config is undefined or not emacs_default_config
