- name: copy rsyslog config file
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - src: "files/10-provider.conf"
      dest: "/etc/rsyslog.d/10-provider.conf"
    - src: "files/15-customize.conf"
      dest: "/etc/rsyslog.d/15-customize.conf"
  notify: Restart rsyslog
