- name: download kanata
  become: true
  ansible.builtin.get_url:
    url: "{{ bin_url }}"
    dest: "{{ bin_dest }}"
    mode: 0755

- name: mkdir config dir
  become: true
  ansible.builtin.file:
    path: "{{ conf_dir }}"
    state: directory
    recurse: true
    owner: root
    group: root

- name: download config
  become: true
  ansible.builtin.get_url:
    url: "{{ conf_url }}"
    dest: "{{ conf_dest }}"
    mode: 0644

- name: install unit file
  become: true
  ansible.builtin.template:
    src: kanata_service.j2
    dest: "{{ unit_file }}"
    owner: root
    group: root

- name: start service
  become: true
  ansible.builtin.systemd_service:
    name: kanata
    enabled: true
    daemon_reload: true
    state: started
