- name: include install tasks for bionic
  include_tasks: bionic.yml
  when: ansible_distribution_release == "bionic"

- name: include install tasks for focal
  include_tasks: focal.yml
  when: ansible_distribution_release == "focal"

- name: include install tasks for hirsute
  include_tasks: hirsute.yml
  when: ansible_distribution_release == "hirsute"

- name: include install tasks for impish
  include_tasks: impish.yml
  when: ansible_distribution_release == "impish"

- name: include install tasks for jammy
  include_tasks: jammy.yml
  when: ansible_distribution_release == "jammy"

- name: include install tasks for noble
  include_tasks: noble.yml
  when: ansible_distribution_release == "noble"

- name: install python package in user
  ansible.builtin.pip:
    name:
      - pipenv
      - black
      - isort
    executable: pip3
    extra_args: --user
  when: ansible_distribution_release in ["bionic", "focal", "hirsute", "impish", "jammy"]

- name: install items by pipx
  community.general.pipx:
    name: "{{ item }}"
  when: ansible_distribution_release in ["noble"]
  loop:
    - pipenv
    - black
    - isort
