- name: install python for bionic
  become: yes
  apt:
    name: "{{ packages_bionic }}"
  when: ansible_facts["distribution_release"] == "bionic"

- name: install python for focal
  become: yes
  apt:
    name: "{{ packages_focal }}"
  when: ansible_facts["distribution_release"] == "focal"

- name: install python package
  become: yes
  pip:
    name: pipenv
    executable: pip3
