- name: prerequisite
  become: yes
  apt:
    name: software-properties-common

- name: add deadsnakes
  become: yes
  apt_repository:
    repo: "{{ repository }}"

- name: install python for bionic
  become: yes
  apt:
    name: "{{ packages_bionic }}"
  when: ansible_facts["distribution_release"] == "bionic"

- name: install python for focal
  become: yes
  apt:
    name: "{{ packages_focal }}"
  when: ansible_distribution_release == "focal"

- name: install python for hirsute
  become: yes
  apt:
    name: "{{ packages_hirsute }}"
  when: ansible_facts["distribution_release"] == "hirsute"

- name: install python for impish
  become: yes
  apt:
    name: "{{ packages_impish }}"
  when: ansible_facts["distribution_release"] == "impish"

- name: install python package in user
  pip:
    name:
      - pipenv
      - black
      - isort
    executable: pip3
    extra_args: --user
