- name: include install tasks for bionic
  include_tasks: bionic.yml
  when: ansible_distribution_release == "bionic"

- name: include install tasks for focal
  include_tasks: focal.yml
  when: ansible_distribution_release == "focal"

- name: include install tasks for hirsute
  include_tasks: hirsute.yml
  when: ansible_distribution_release == "hirsute"

- name: include install tasks for impish
  include_tasks: impish.yml
  when: ansible_distribution_release == "impish"

- name: install python package in user
  pip:
    name:
      - pipenv
      - black
      - isort
    executable: pip3
    extra_args: --user
