- name: clone repository
  git:
    dest: ~/.config/chemacs/cask
    repo: https://github.com/tateishi/emacs-cask.git

- name: cask install
  shell: ~/.cask/bin/cask install
  args:
    chdir: ~/.config/chemacs/cask

- name: cask update
  shell: ~/.cask/bin/cask update
  args:
    chdir: ~/.config/chemacs/cask

- name: cask upgrade
  shell: ~/.cask/bin/cask upgrade
  args:
    chdir: ~/.config/chemacs/cask
